UPDATE "app_settings"
SET "sitePages" = jsonb_set(
  COALESCE("sitePages", '{}'::jsonb),
  '{about}',
  '{"slug":"about","title":"About Us","lastUpdated":"September 19, 2026","content":"About Us\n\nCrafting Timeless Heritage, Delivered Straight from Our Loom to Your Home.\n\nWelcome to WOLHOMES. We are master rug makers and artisans dedicated to the timeless art of handcrafted floor coverings.\n\nOur journey began in 1990 as a family tradition deeply rooted in perfecting ancient weaving techniques—specifically Tibetan Hand-Knotted and premium Hand-Tufted rug-making. Over the decades, our skilled artisans passed down these traditional skills from generation to generation. Building upon this 35+ years of heritage, our firm was formally registered in 2017 as a modern manufacturing unit, allowing us to serve global clients with structured quality standards.\n\nWhy Buyers & Interior Designers Worldwide Choose Us\n\nMaster Craftsmanship: Every rug we produce is a work of art. From intricate Tibetan hand-knotted patterns to luxurious hand-tufted textures, our master weavers pour exceptional skill, precision, and dedication into every piece.\n\nDirect Factory-to-Doorstep Model: Based in our manufacturing facility at Devpurwa Road, Mirzapur, Uttar Pradesh (India), we manage the entire production process in-house—from raw material selection to weaving, washing, and final quality inspection. Delivering directly from our factory to your door eliminates unnecessary middlemen and guarantees true factory-direct pricing.\n\nCustom & Bespoke Rugs: Because we own and operate our manufacturing factory, we offer full customization for trade professionals, architects, interior designers, and individual buyers worldwide. Whether you require a unique size, specific color palette, or custom design, we build your rug exactly to your specifications.\n\nGlobal Door-to-Door Delivery: We cater to rug lovers across the globe, providing reliable, fully tracked door-to-door shipping straight from our looms in India to your address, anywhere in the world.\n\nOur Promise\n\nWhether you are seeking a statement Tibetan hand-knotted heirloom or a bespoke hand-tufted rug crafted for your space, WOLHOMES promises uncompromised quality, authentic craftsmanship, and a seamless shopping experience from our factory to your home.\n\nFactory Address: Devpurwa Road, Mirzapur, Uttar Pradesh, India\n\nCustomer Care: info@wolhomes.com"}'::jsonb,
  true
),
"updatedAt" = CURRENT_TIMESTAMP
WHERE "id" = 'default';
