UPDATE "app_settings"
SET "sitePages" = jsonb_set(
  COALESCE("sitePages", '{}'::jsonb),
  '{returns}',
  '{"slug":"returns","title":"Return & Refund Policy","lastUpdated":"September 19, 2026","content":"Return & Refund Policy\n\nThank you for shopping with us! We want you to love your purchase. If you are not completely satisfied, we are here to help.\n\n14-Day Return Window\n\nWe offer a 14-day return policy. You have 14 days from the date you receive your item to request a return.\n\nTo be eligible for a return:\n\nYour item must be unused, unworn, and in the same condition that you received it.\n\nIt must be in the original packaging with all tags attached.\n\nProof of purchase (order number or receipt) is required.\n\nNon-Returnable Items (Custom & Personalized Orders)\n\nPlease note that Custom and Personalized Orders CANNOT be returned or exchanged.\n\nWhy? Custom items are specially made-to-order according to your unique specifications, measurements, or designs, making them non-resalable.\n\nDefective or Damaged Custom Orders: If your custom item arrives damaged, defective, or incorrect due to our error, please contact us within 48 hours of delivery with photos, and we will immediately send a free replacement or issue a full refund.\n\nHow to Initiate a Return\n\nContact Us: Send an email to info@wolhomes.com with your Order ID and the reason for the return.\n\nGet Approval: Our team will review your request and send you the return shipping instructions and factory return address.\n\nShip the Item: Package the item securely and send it back to our factory using a trackable shipping method.\n\nImportant Return Shipping & Duty Notice:\n\nThe buyer is solely responsible for paying all return shipping charges, including any applicable customs duties, taxes, and import fees required to deliver the package directly to our Factory (Delivered Duty Paid / DDP). Returns shipped with unpaid duties or postage-due will not be accepted at our factory. (Note: Return shipping fees will only be covered by us if the item arrived damaged, defective, or incorrect).\n\nRefunds\n\nOnce we receive and inspect your returned item at our factory, we will notify you via email regarding the approval or rejection of your refund.\n\nIf approved, your refund will be processed immediately to your original method of payment (Credit Card, PayPal, etc.).\n\nPlease allow 3 to 7 business days for the refund to reflect in your bank account, depending on your card issuer.\n\nDamaged, Defective, or Incorrect Items\n\nPlease inspect your order upon arrival. If the item is defective, damaged, or if you received the wrong item, contact us immediately at info@wolhomes.com so we can evaluate the issue and make it right for you.\n\nContact Us\n\nIf you have any questions about our Return Policy, please reach out to us:\n\nEmail: info@wolhomes.com\n\nCustomer Support Hours: Monday - Friday (9 AM - 5 PM EST)\n\nFactory Address: 575/2-C, Devpurwa Road, Mirzapur, Uttar Pradesh, India"}'::jsonb,
  true
),
"updatedAt" = CURRENT_TIMESTAMP
WHERE "id" = 'default';
